export const categories = [
  {
    emoji: "🍔",
    title: "Alimentação",
    quantity: 15,
    limit: 500,
    spent: 420,
    remaining: 80,
  },
  {
    emoji: "🚗",
    title: "Transporte",
    quantity: 10,
    limit: 300,
    spent: 250,
    remaining: 50,
  },
  {
    emoji: "🍻",
    title: "Lazer",
    quantity: 5,
    limit: 200,
    spent: 120,
    remaining: 80,
  },
  {
    emoji: "🏠",
    title: "Moradia",
    quantity: 1,
    limit: 1200,
    spent: 1000,
    remaining: 200,
  },
  {
    emoji: "🏥",
    title: "Saúde",
    quantity: 3,
    limit: 400,
    spent: 300,
    remaining: 100,
  },
  {
    emoji: "👔",
    title: "Vestuário",
    quantity: 8,
    limit: 350,
    spent: 280,
    remaining: 70,
  },
  {
    emoji: "📚",
    title: "Educação",
    quantity: 2,
    limit: 800,
    spent: 600,
    remaining: 200,
  },
  {
    emoji: "💅",
    title: "Beleza",
    quantity: 4,
    limit: 150,
    spent: 100,
    remaining: 50,
  },
  {
    emoji: "💸",
    title: "Outras",
    quantity: 7,
    limit: 250,
    spent: 180,
    remaining: 70,
  },
];
