name: Treasure CI

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        run: npm test
